### ISSUE TITLE
phpunit configuration file

### ISSUE THREAD

**Issue by remicollet** [tecnickcom/tc-lib-file#3]
Report from PHPUnit 7.2 (which now includes a schema check)

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

```
  Line 12:
  - Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.

  Line 24:
  - Element 'log', attribute 'charset': The attribute 'charset' is not allowed.

  Line 25:
  - Element 'log', attribute 'charset': The attribute 'charset' is not allowed.

  Line 26:
  - Element 'log', attribute 'logIncompleteSkipped': The attribute 'logIncompleteSkipped' is not allowed.

  Test results may not be as expected.
```

**Comment by fokosun** [comment]
same here, I am wondering why this is happening. To remove this warning I had to remove `syntaxCheck` from my phpunit.xml.dist file

**Comment by michaelcurry** [comment]
Happening here as well, and I don't see any documentation talking about breaking changes or deprecated attribute...

**Comment by nicolaasuni** [comment]
I have fixed this in the latest version.

**Comment by Goahnary** [comment]
I am writing a feature for phpunit. I get these errors as well. @nicolaasuni did you have to add the new attributes to a list or something?

**Comment by Goahnary** [comment]
Okay I figured out you have to change the `phpunit.xsd` file to accept your attribute.
e.g. I added:
```
<xs:attribute name="timestamps" type="xs:boolean" default="false"/>
```
Leaving this here for others who may run across this thread with the same question.

**Comment by dragondiego7** [comment]
hey, i has the same problem with phpunit 8. This working for me. Thanks

**Comment by rermolaev** [comment]
Hello.
_________________________________________________________
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 7:
  - Element 'phpunit', attribute 'convertNotiesToExceptions': The attribute 'convertNotiesToExceptions' is not allowed.

  Test results may not be as expected.
_________________________________________________________

The "convertNotciesToExceptions" attribute exists in the validation file. There's a mismatch in the phpunit.xsd and phpunit.xml.dist
_________________________________________________________
I added the second string of two these (phpunit.xsd):
        <xs:attribute name="convertNoticesToExceptions" type="xs:boolean" default="true"/>
        <xs:attribute name="convertNotiesToExceptions" type="xs:boolean" default="true"/>

And I added the first string of two these (phpunit.xml.dist):
         convertNotiсesToExceptions="true"
         convertNotiesToExceptions="true"

But was it correct way to solve this problem?
_________________________________________________________
Thank you.
