### ISSUE TITLE
PHPUnit 7.2.6 configuration file

### ISSUE THREAD

**Issue by Relaxe111** [tecnickcom/tc-lib-file#4]
Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 11:
  - Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.

  Test results may not be as expected.

**Comment by nicolaasuni** [comment]
There is no such attribute in the last version.
Are you using the latest version?
Are you using a custom phpunit.xml file?

**Comment by Relaxe111** [comment]
Yes I'm using HPUnit 7.2.6 delivered with lumen, i have not made changes in phpunit.xml file. I solved the problem by deleting this attribute and have no more warnings. Hope this is right solution)

**Comment by Relaxe111** [comment]
find out at Lumen deliver phpunit.xml file different from latest version of phpunit so thats is the problem. I just copy/paste content of phpunit.xml from an laravel project on to  my file and no more problems
